version: '3.1'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  rc:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      RDBMS_HOST: host.docker.internal
    ports:
      - 4000:4000
    volumes:
      - ./:/data
